apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: product-catalog

configMapGenerator:
- name: server
  files:
    - config/application.properties

resources:
  - default-view-rolebinding.yaml
  - knative-service.yaml