apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image
spec:
  params:
  - name: src-image
    type: string
  - name: dest-image
    type: string
  - name: dest-tags
    type: string
    default: ""
  steps:
    - name: run-commands
      image: quay.io/gnunn/skopeo:latest
      script: |
        #!/usr/bin/env bash
        TOKEN="$(oc whoami -t)"
        USER="pipeline"

        # echo "Copying image docker://$(params.src-image) to docker://$(params.dest-image):latest"
        # skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds="${USER}:${TOKEN}" --dest-authfile=/workspace/dest/.docker/config.json docker://$(params.src-image) docker://$(params.dest-image):latest

        if [ "$(params.dest-tags)" != "" ];
        then

          tags=$(params.dest-tags)
          for i in ${tags//,/ }
          do
            echo "Copying image docker://$(params.src-image) to docker://$(params.dest-image):$i"
            skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds="${USER}:${TOKEN}" --dest-authfile=/workspace/dest/.docker/config.json docker://$(params.src-image) docker://$(params.dest-image):$i
          done
        fi
      volumeMounts:
        - name: dest-docker-config
          mountPath: /workspace/dest/.docker/
  volumes:
    - name: dest-docker-config
      secret:
        secretName: dest-docker-config
        items:
          - key: .dockerconfigjson
            path: config.json