apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-prod
nameSuffix: -prod

commonLabels:
  app: product-catalog-prod

bases:
- ../../base

resources:
- namespace.yaml

patchesJson6902:
- target:
    version: v1beta1
    group: app.k8s.io
    kind: Application
    name: product-catalog
  path: patch-application.yaml
- target:
    version: v1
    group: apps.open-cluster-management.io
    kind: Subscription
    name: product-catalog
  path: patch-subscription.yaml