apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
- ../../../../../manifests/tools/argocd/base


commonLabels:
  gitops.ownedBy: apps-product-catalog

patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-dev
  path: patch-project.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-test
  path: patch-project.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-prod
  path: patch-project.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-cicd
  path: patch-project.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-monitor
  path: patch-project.yaml
