
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../overlays/default

namespace: product-catalog-cicd

resources:
- docker-dest-secret.yaml

patchesStrategicMerge:
  - patch-image-resources.yaml
