apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: server
spec:
  workspaces:
    - name: git-source
  params:
    - name: git_revision
      type: string
      default: master
    - name: git_url
      type: string
      default: https://github.com/gnunn-gitops/product-catalog-server
    - name: MAVEN_MIRROR_URL
      default: ""
    - name: image_dest_url
      type: string
      description: External registry location to copy image to
      default: quay.io/gnunn/server
    - name: push-to-prod
      description: "Set to true if you want the pipeline to create a PR to push to prod"
      type: string
      default: "false"
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.git_url)"
        - name: revision
          value: "$(params.git_revision)"
        - name: deleteExisting
          value: "true"
    - name: generate-id
      taskRef:
        name: generate-id
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: git-source
    - name: build
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - generate-id
      params:
        - name: MAVEN_MIRROR_URL
          value: "$(params.MAVEN_MIRROR_URL)"
        - name: GOALS
          value: "package"
        - name: ARGUMENTS
          value: "-DskipTests"
    - name: unit-test
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - build
      params:
        - name: MAVEN_MIRROR_URL
          value: "$(params.MAVEN_MIRROR_URL)"
        - name: GOALS
          value: "test"
    - name: quality
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - build
      params:
        - name: MAVEN_MIRROR_URL
          value: "$(params.MAVEN_MIRROR_URL)"
        - name: GOALS
          value: "sonar:sonar"
        - name: PROFILES
          value: "quality"
    - name: install-nexus
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - unit-test
        - quality
      params:
        - name: MAVEN_MIRROR_URL
          value: "$(params.MAVEN_MIRROR_URL)"
        - name: GOALS
          value: "install"
    - name: build-image
      taskRef:
        name: binary-s2i
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - unit-test
        - quality
      params:
        - name: file
          value: "$(workspaces.source.path)/target/*-runner.jar"
        - name: buildconfig
          value: server
    - name: tag-image
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-image
      params:
        - name: SCRIPT
          value: |
            oc tag server:latest server:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
    - name: push-dev-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - tag-image
        - install-nexus
      params:
        - name: src-image
          value: image-registry.openshift-image-registry.svc:5000/product-catalog-cicd/server:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
        - name: dest-image
          value: $(params.image_dest_url)
        - name: dest-tags
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid),dev
    - name: deploy-dev
      taskRef:
        name: deploy
      runAfter:
        - push-dev-image
      params:
        - name: NAME
          value: server
        - name: NAMESPACE
          value: product-catalog-dev
    - name: dev-test
      taskRef:
        name: newman
      runAfter:
        - deploy-dev
      params:
        - name: COLLECTION
          value: https://raw.githubusercontent.com/gnunn-gitops/product-catalog-server/master/tests/product-catalog-server-tests.json
        - name: ENVIRONMENT
          value: newman-dev-env.json
    - name: push-test-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - dev-test
      params:
        - name: src-image
          value: image-registry.openshift-image-registry.svc:5000/product-catalog-cicd/server:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
        - name: dest-image
          value: $(params.image_dest_url)
        - name: dest-tags
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid),test,latest
    - name: deploy-test
      taskRef:
        name: deploy
      runAfter:
        - push-test-image
      params:
        - name: NAME
          value: server
        - name: NAMESPACE
          value: product-catalog-test
    - name: test-test
      taskRef:
        name: newman
      runAfter:
        - deploy-test
      params:
        - name: COLLECTION
          value: https://raw.githubusercontent.com/gnunn-gitops/product-catalog-server/master/tests/product-catalog-server-tests.json
        - name: ENVIRONMENT
          value: newman-test-env.json
    - name: create-prod-pr
      taskRef:
        name: tkn
        kind: Task
      conditions:
        - conditionRef: "push-to-prod"
          params:
            - name: "push"
              value: "$(params.push-to-prod)"
      runAfter:
        - test-test
      params:
        - name: commands
          value: |
            tkn pipeline start push-prod-pr --prefix-name server -p image_dest_tag=$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid) -p image_dest_url=quay.io/gnunn/server -p cluster=ocplab -p app=server -s github-pipeline -w name=git-source,claimName=manifest-source