apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: client
spec:
   workspaces:
    - name: app-binary
   resources:
    - name: source
      type: git
   tasks:
    - name: build
      taskRef:
        name: npm
      workspaces:
        - name: app-binary
          workspace: app-binary
      resources:
        inputs:
        - name: source
          resource: source
    - name: build-image
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: app-binary
      runAfter:
        - build
      params:
        - name: COMMANDS
          value: |
              ls $(workspaces.app-binary.path)
              oc start-build client --from-dir=$(workspaces.app-binary.path) --wait=true
    - name: tag-dev-image
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: app-binary
      runAfter:
        - build-image
      params:
        - name: COMMANDS
          value: |
              oc tag product-catalog-cicd/client:latest product-catalog-dev/client:latest
    - name: deploy-dev
      taskRef:
        name: deploy
        kind: Task
      runAfter:
        - tag-dev-image
      params:
        - name: NAME
          value: client
        - name: NAMESPACE
          value: product-catalog-dev
    - name: tag-test-image
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: app-binary
      runAfter:
        - deploy-dev
      params:
        - name: COMMANDS
          value: |
              oc tag product-catalog-dev/client:latest product-catalog-test/client:latest
    - name: deploy-test
      taskRef:
        name: deploy
        kind: Task
      runAfter:
        - tag-test-image
      params:
        - name: NAME
          value: client
        - name: NAMESPACE
          value: product-catalog-test