apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yq
spec:
  workspaces:
    - name: source
  params:
    - name: command
      type: string
      description: The set of commands to run
  steps:
    - name: yq
      workingDir: $(workspaces.source.path)
      image: mikefarah/yq:3.3.2
      script: |
        #!/usr/bin/env bash
        $(params.COMMANDS)