apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven
spec:
  workspaces:
  - name: app-binary
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run, space spearated
      type: string
      default: "package"
    - name: PROFILES
      description: The Maven maven profiles to activate, comma separated
      type: string
      default: ""
    - name: MAVEN_MIRROR_URL
      description: The Maven bucketrepo- mirror
      type: string
      default: ""
    - name: MAVEN_REPO_CREDS_SECRET
      type: string
      description: name of the secret holding the maven repo credentials
      default: maven-repo-creds
    - name: M2_DIRECTORY
      type: string
      description: Location of M2 directory, do not change
      default: /tekton/home/.m2
    resources:
    - name: source
      targetPath: /
      type: git
  steps:
    - name: mvn-settings
      image: docker.io/maven:3.6.3-jdk-8
      command:
        - '/bin/bash'
        - '-c'
      args:
        - |-
          [[ -f $(inputs.params.M2_DIRECTORY)/settings.xml ]] && \
          echo 'using existing $(inputs.params.M2_DIRECTORY)/settings.xml' && \
          cat $(inputs.params.M2_DIRECTORY)/settings.xml && exit 0

          [[ -n '$(inputs.params.MAVEN_MIRROR_URL)' ]] && \
          cat > $(inputs.params.M2_DIRECTORY)/settings.xml <<EOF
          <settings>
            <mirrors>
              <mirror>
                <id>mirror.default</id>
                <name>mirror.default</name>
                <url>$(inputs.params.MAVEN_MIRROR_URL)</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>
          EOF

          [[ -f $(inputs.params.M2_DIRECTORY)/settings.xml ]] && cat $(inputs.params.M2_DIRECTORY)/settings.xml
          [[ -f $(inputs.params.M2_DIRECTORY)/settings.xml ]] || echo skipping settings
      volumeMounts:
        - name: m2-repository
          mountPath: $(inputs.params.M2_DIRECTORY)
        - name: maven-settings
          mountPath: $(inputs.params.M2_DIRECTORY)/settings.xml
          subPath: settings.xml
    - name: mvn-goals
      image: docker.io/maven:3.6.3-jdk-8
      command:
        - '/bin/bash'
        - '-c'
      args:
        - |-
          if [[ -z "${param// }" ]]; then
            mvn $(inputs.params.GOALS) -P$(inputs.params.PROFILES)
          else
            mvn $(inputs.params.GOALS)
          fi
      env:
        - name: MAVEN_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.MAVEN_REPO_CREDS_SECRET)
              key: username
        - name: MAVEN_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.MAVEN_REPO_CREDS_SECRET)
              key: password
      volumeMounts:
        - name: m2-repository
          mountPath: $(inputs.params.M2_DIRECTORY)
        - name: maven-settings
          mountPath: $(inputs.params.M2_DIRECTORY)/settings.xml
          subPath: settings.xml
    - name: mvn-copy-dist
      image: docker.io/maven:3.6.3-jdk-8
      command:
        - '/bin/bash'
        - -c
      args:
        -  |-
          echo "Remove old versions..."
          rm $(workspaces.app-binary.path)/*
          echo "Copy new version..."
          cp -R /workspace/target/*-runner.jar $(workspaces.app-binary.path)
  volumes:
    - name: m2-repository
      persistentVolumeClaim:
        claimName: m2-cache
    - name: maven-settings
      configMap:
        name: maven-settings