apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-id
spec:
  workspaces:
    - name: source
  results:
  - description: The short commit SHA that was fetched by this Task
    name: short_commit
  - description: Unique build identifier
    name: build_uid
  - description: Unique tag identifier
    name: tag_id
  steps:
  - name: generate
    workingDir: $(workspaces.source.path)
    image: quay.io/gnunn/tools:latest
    script: |
      #!/usr/bin/env sh

      # Get short commit
      export SHORT_SHA=$(git rev-parse --short HEAD)
      echo -n "$SHORT_SHA" > $(results.short_commit.path)

      # Generate uinque UID
      #export BUILD_UID=$(printf '%s ' $(date) | cksum | cut -f -1 -d ' ')
      export BUILD_UID=$(ksuid)
      echo -n "$BUILD_UID" > $(results.build_uid.path)

      echo -n "$SHORT_SHA-$BUILD_UID" > $(results.tag_id.path)

      echo "Generated ID $SHORT_SHA-$BUILD_UID"