apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: client
spec:
   resources:
    - name: source
      type: git
    - name: internal-image
      type: image
    - name: repository-image
      type: image
   tasks:
    - name: build
      taskRef:
        name: npm
      workspaces:
        - name: app-binary
          workspace: app-binary
      resources:
        inputs:
        - name: source
          resource: source
    - name: build-image
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: app-binary
      runAfter:
        - build
      params:
        - name: COMMANDS
          value: |
              ls $(workspaces.app-binary.path)
              oc start-build client --from-dir=$(workspaces.app-binary.path) --wait=true
    - name: promote-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - build-image
      resources:
        inputs:
        - name: src-image
          resource: internal-image
        - name: dest-image
          resource: repository-image
    - name: deploy-dev
      taskRef:
        name: deploy
        kind: Task
      runAfter:
        - promote-image
      params:
        - name: NAME
          value: client
        - name: NAMESPACE
          value: product-catalog-dev
    - name: deploy-test
      taskRef:
        name: deploy
        kind: Task
      runAfter:
        - deploy-dev
      params:
        - name: NAME
          value: client
        - name: NAMESPACE
          value: product-catalog-test