apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: client
  generateName: client-
spec:
  pipelineRef:
    name: client
  resources:
    - name: source
      resourceRef:
        name: client
  workspaces:
  - name: app-binary
    persistentVolumeClaim:
      claimName: client-binary