apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: server
  generateName: server-
spec:
  pipelineRef:
    name: server
  resources:
    - name: source
      resourceRef:
        name: server
  params:
    - name: MAVEN_MIRROR_URL
      value: http://nexus:8081/content/groups/public/
      #value: ""
  workspaces:
  - name: app-binary
    persistentVolumeClaim:
      claimName: server-binary