apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../environments/overlays/monitor-no-prometheus

resources:
- user1-rolebinding.yaml
# - prometheus-role-binding.yaml
