apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../manifests/pipelines/overlays/quay
- ../../../../manifests/triggers/overlays/default

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
#   - name: dest-docker-config
#     type: kubernetes.io/dockerconfigjson
#     files:
#       - secrets/.dockerconfigjson

resources:
- pipeline-rolebinding.yaml
- user1-rolebinding.yaml
- docker-sealed-secret.yaml