apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: client
  generateName: client-
spec:
  pipelineRef:
    name: client
  params:
    - name: push-to-prod
      value: "false"
  workspaces:
  - name: git-source
    persistentVolumeClaim:
      claimName: client-source
  - name: newman-env
    configMap:
      name: newman-env