apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-test

bases:
- ../../base

# resources:
# - namespace.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: client
  path: patch-client-deployment.yaml

- target:
    group: apps
    version: v1
    kind: Deployment
    name: server
  path: patch-server-deployment.yaml
