apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- cluster-role.yaml
- session-secret.yaml
- prometheus.yaml
- prometheus-quarkus-sm.yaml
# - prometheus-route.yaml